server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            #- After=2020-04-27T17:02:17.990+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
           # - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
           # - Host=**.atguigu.com
            #- Method=GET
            #- Quert=username, \d+ #要带有参数名为username ，并且参数必须为整数
            #- RemoteAddr=192.168.1.1/24 #要带有参数主机IP地址和一个子网掩码

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true

